### ISSUE TITLE
builder.py issues 2

### ISSUE THREAD

**Issue by fuadinridho** [YosysHQ/oss-cad-suite-build#36]
hi, im trying to build with "./builder.py build" by. but i got an error in the process. trying to solve it but don;t get the solution yet. can you help me?

...  
-> [amaranth-boards] Checkout origin/main ...
  -> [amaranth-boards] Current revision 2d0a23b75ebb769874719297dec65ff07ca9e79f ...
  -> [migen] Updating https://github.com/m-labs/migen ...
  -> [migen] Checkout origin/master ...
  -> [migen] Current revision d4e3f34177c32f09904397179e6ed9c83175e528 ...
  -> [cocotb] Updating https://github.com/cocotb/cocotb ...
  -> [cocotb] Checkout origin/master ...
  -> [cocotb] Current revision 1ca0dfff36c04bc657ef87645362292a377c8f68 ...
==> Building default for linux-x64 architecture ...
==> Step [ 1/53] building python3 ...
  -> Remove old output dir ...
  -> Creating output dir ...
  -> Remove old build dir ...
  -> Creating build dir ...
  -> Copy 'python3' source to build dir ...
  -> Compiling ...
bash: /tmp/tmpttu20t_f: No such file or directory

==> ERROR : Script returned error code 127.

**Comment by mmicko** [comment]
Hard to tell by this output, but check if you have `docker` installed and able to run it as current user.
You can find more info about this at: https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user

Not sure why you need to build all locally but this script is mostly made so that GitHub Actions can run them and create packages. I also use it locally to test build scripts when new package is added, or if there are changes needed to fix build.
If you are developing support for some new package please give more info about it.
